### ISSUE TITLE
User Story : Users can delete their profile

### ISSUE THREAD

**Issue by mattcooperdev** [mattcooperdev/Wavey#16]
As a **User** I can **delete my profile** so that **I can remove my data and posts at my request**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a registered User
	**When** I am logged in to my account 
	**Then** I have the option to delete my account

- Acceptance Criteria 2
	**Given** that I am a registered User
	**When** I click on the option to delete my account
	**Then** I have to confirm that I wish to do so

- Acceptance Criteria 3
	**Given** that I am a registered User
	**When** I have confirmed that I wish to delete my account
	**Then** my profile and all data associated with it is deleted 

- Acceptance Criteria 4
	**Given** that I am a registered User
	**When** the account is full deleted
	**Then** I receive a confirmation that this action has taken place

## Tasks
- [x] On User profile page give a button to delete the account 
- [x] Create a confirmation request to User before the delete is actioned
- [x] Once confirmed, account and all associated data is deleted
- [x] Develop a method of communicating the delete action to the User (ie Email)
