### ISSUE TITLE
User Story : Responsive Design

### ISSUE THREAD

**Issue by mattcooperdev** [mattcooperdev/Wavey#24]
As a **Site Owner** I want **my Site to be fully responsive** so that **visitors to the Site have a good experience on any device**

## Acceptance Criteria

- Acceptance Criteria 1
	**Given** I am a user is accessing the Site on a smartphone
	**When** I navigate through the Site
	**Then** all pages are correctly formatted
- Acceptance Criteria 2
	**Given** I am a user is accessing the Site on a tablet
	**When** I navigate through the Site
	**Then** all pages are correctly formatted
- Acceptance Criteria 3
	**Given** I am a user is accessing the Site on a laptop
	**When** I navigate through the Site
	**Then** all pages are correctly formatted
- Acceptance Criteria 4
	**Given** I am a user is accessing the Site on a desktop
	**When** I navigate through the Site
	**Then** all pages are correctly formatted

## Tasks
- [x] Develop all pages to be responsive on smartphones
- [x] Develop all pages to be responsive on tablets
- [x] Develop all pages to be responsive on laptops
- [x] Develop all pages to be responsive on desktop
- [x] Develop accessibility for screen readers
